// This file is auto-generated by YooAsset AssetCodeGenerator
// Do not modify this file - your changes will be lost

namespace GDFramework.FrameData
{

   public struct DefaultPackage
    {

       public struct Config
       {

           public struct ChunkDataAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_configs_chunkdata";
               public const string Dungeon_DEF_3E4C63EC = "yoo:Dungeon_DEF_3E4C63EC";
               public const string Region_DEF_5B242D32 = "yoo:Region_DEF_5B242D32";
               public const string Room_DEF_FAFFF67E = "yoo:Room_DEF_FAFFF67E";
               public const string Universe_DEF_97E4249B = "yoo:Universe_DEF_97E4249B";
               public const string World_DEF_D577D412 = "yoo:World_DEF_D577D412";
           }

           public struct GameInputAssetGroup
           {
               public const string BundleName = "defaultpackage_gdframework_res_input_gameinput.inputactions";
               public const string GameInput = "yoo:GameInput";
           }

           public struct TbmultilingualAssetGroup
           {
               public const string BundleName = "defaultpackage_gdframework_res_mul_tbmultilingual.json";
               public const string Tbmultilingual = "yoo:Tbmultilingual";
           }

           public struct EntityDataAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_configs_entitydata";
           }
       }

       public struct UI
       {

           public struct UI_GameMenuPanelAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_prefabs_view_ui_gamemenupanel.prefab";
               public const string UI_GameMenuPanel = "yoo:UI_GameMenuPanel";
           }
       }

       public struct UIDetails
       {

           public struct DetailsAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_prefabs_view_details";
               public const string UI_TipsWindow = "yoo:UI_TipsWindow";
           }
       }

       public struct Music
       {

           public struct BGMAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_musics_bgm";
               public const string Danager_01 = "yoo:Danager_01";
               public const string Dungeon_01 = "yoo:Dungeon_01";
               public const string Dungeon_02 = "yoo:Dungeon_02";
               public const string in_pursuit_383246 = "yoo:in-pursuit-383246";
           }

           public struct InteractAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_musics_interact";
               public const string ui_click_43196 = "yoo:ui-click-43196";
           }
       }

       public struct Particle
       {
       }

       public struct Prefabs
       {

           public struct UniverseControllerAssetGroup
           {
               public const string BundleName = "defaultpackage_core_res_prefabs_universecontroller.prefab";
               public const string UniverseController = "yoo:UniverseController";
           }
       }

       public struct Sprite
       {
       }
    }
}
